version: '3'

services:
  nginx:
    build: .
    container_name: natif-api-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  letsencrypt: